### ISSUE TITLE
nodejs12 no longer supported 

### ISSUE THREAD

**Issue by logbookcreation** [aws-samples/happy-path#20]
I'm a rookie, so it's possible these aren't real issues or maybe experts just can work around them. 
I started with a blank slate in Cloud9. 

Encountered two errors during deploy in step 3.

1. `The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID:  `
2. Resource handler returned message: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10]. (Service: Lambda, Status Code: 400, Request ID:       

Fixed 1. by updating nodejs12 to nodejs18 pretty much anywhere I could find it that wasn't build.
Fixed 2. by removing the "ReservedConcurrentExecutions". Though it appears that could also be fixed by increasing limits on Lambda functions (mine was set to 10). Probably worth leaving this there as I guess it's a security thing.
![Screenshot 2024-01-06 at 3 04 55 PM](https://github.com/aws-samples/happy-path/assets/143049762/d3a605ed-3e8d-44f0-9236-1ab938ce5a57)

Thanks for the project! Been interesting to try to work through.

**Comment by jbesw** [comment]
Thanks for raising - the currently supported version of Node is 18. If you update this in the IaC, it should deploy with the latest version of the SAM CLI.
